alpha: 1.0
beam_size: 10
checkpoint_path: /home/xgy/net/CoMER-TD/lightning_logs/version_236/checkpoints/epoch=79-step=547279-val_ExpRate=0.4047.ckpt
cross_coverage: true
d_model: 256
dc: 32
dim_feedforward: 1024
dropout: 0.3
early_stopping: false
growth_rate: 24
learning_rate: 0.08
max_len: 100
nhead: 8
num_decoder_layers: 3
num_layers: 16
num_tree_decoder_layer: 3
patience: 20
self_coverage: true
temperature: 1.0
threshold: 0.5
